// ReAmped Facebook Marketplace Fetcher
//
// Facebook Marketplace exposes a public GraphQL search endpoint that does NOT
// require authentication for location-based browsing.  We query it for used
// musical-instrument categories, normalise results, and upsert into listings.
//
// Rate-limit note: FB will rate-limit aggressive scrapers.  We use a 5-second
// inter-request delay and a 90-minute cron cadence (set in server.js).
//
// FB's internal API surface changes without notice.  If this starts returning
// empty results, check the doc_id / variable shape against current traffic.

const axios = require('axios');
const { Pool } = require('pg');
const { scoreListings } = require('../services/scorer');
const { normalizeCondition, cleanText, parsePrice } = require('../utils/normalizers');
const logger = require('../utils/logger');

const db = new Pool({ connectionString: process.env.DATABASE_URL });

// US ZIP codes to cycle through — covers major metro areas
const LOCATIONS = [
  { zip: '10001', name: 'New York, NY',     lat: 40.7506,  lng: -73.9971  },
    { zip: '90001', name: 'Los Angeles, CA',  lat: 33.9731,  lng: -118.2479 },
      { zip: '60601', name: 'Chicago, IL',      lat: 41.8827,  lng: -87.6233  },
        { zip: '77001', name: 'Houston, TX',      lat: 29.7543,  lng: -95.3677  },
          { zip: '85001', name: 'Phoenix, AZ',      lat: 33.4484,  lng: -112.0740 },
            { zip: '19101', name: 'Philadelphia, PA', lat: 39.9526,  lng: -75.1652  },
              { zip: '78201', name: 'San Antonio, TX',  lat: 29.4241,  lng: -98.4936  },
                { zip: '92101', name: 'San Diego, CA',    lat: 32.7157,  lng: -117.1611 },
                  { zip: '75201', name: 'Dallas, TX',       lat: 32.7767,  lng: -96.7970  },
                    { zip: '95101', name: 'San Jose, CA',     lat: 37.3382,  lng: -121.8863 },
                    ];

                    const SEARCH_QUERIES = [
                      { q: 'electric guitar',  category: 'guitar'         },
                        { q: 'bass guitar',      category: 'bass'           },
                          { q: 'guitar amp amplifier', category: 'amp'        },
                            { q: 'effects pedal',    category: 'pedal'          },
                              { q: 'keyboard synthesizer', category: 'keys'       },
                                { q: 'drum kit snare',   category: 'drum'           },
                                  { q: 'acoustic guitar',  category: 'acoustic-guitar'},
                                    { q: 'audio interface recording', category: 'recording' },
                                    ];

                                    // Facebook Marketplace public search endpoint (mobile API — no login required)
                                    const FB_SEARCH_URL = 'https://www.facebook.com/api/graphql/';

                                    const FB_HEADERS = {
                                      'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1',
                                        'Accept': '*/*',
                                          'Accept-Language': 'en-US,en;q=0.9',
                                            'Content-Type': 'application/x-www-form-urlencoded',
                                              'Origin': 'https://www.facebook.com',
                                                'Referer': 'https://www.facebook.com/marketplace/',
                                                  'X-FB-Friendly-Name': 'CometMarketplaceSearchContentPaginationQuery',
                                                  };

                                                  async function searchFbMarketplace(query, location, cursor = null) {
                                                    const variables = JSON.stringify({
                                                        buyLocation: { latitude: location.lat, longitude: location.lng },
                                                            contextual_data: null,
                                                                count: 24,
                                                                    cursor,
                                                                        flashSaleEventID: '',
                                                                            hasImage: true,
                                                                                itemCondition: null,
                                                                                    locale: null,
                                                                                        maxPrice: null,
                                                                                            minPrice: null,
                                                                                                numericVerticalFields: [],
                                                                                                    numericVerticalFieldFilters: [],
                                                                                                        priceRange: null,
                                                                                                            query,
                                                                                                                radius: 80467, // 50 miles in metres
                                                                                                                    savedSearchID: '',
                                                                                                                        savedSearchQuery: query,
                                                                                                                            scale: 2,
                                                                                                                                shouldIncludePopularSearches: false,
                                                                                                                                    stringVerticalFields: [],
                                                                                                                                        topicPageParams: { location_id: location.zip, url: 'instruments' },
                                                                                                                                            virtualContextualUserId: null,
                                                                                                                                              });
                                                                                                                                              
                                                                                                                                                const params = new URLSearchParams({
                                                                                                                                                    av: '0',
                                                                                                                                                        __user: '0',
                                                                                                                                                            __a: '1',
                                                                                                                                                                __req: '1',
                                                                                                                                                                    __hs: '19624.HYP:comet_pkg.2.1.0.0.0',
                                                                                                                                                                        dpr: '2',
                                                                                                                                                                            __ccg: 'EXCELLENT',
                                                                                                                                                                                __rev: '1010210494',
                                                                                                                                                                                    __s: 'x0sr0d:g35gj0:gf4i3a',
                                                                                                                                                                                        __hsi: '7356401855820278304',
                                                                                                                                                                                            __dyn: '7xe6EaU2mUb8uhpUW3q32-360CEbo9UaEW2O0EE2awgo9o1nEhU2fwxyo68K3wcz8kw',
                                                                                                                                                                                                __csr: '',
                                                                                                                                                                                                    fb_dtsg: process.env.FB_DTSG || '',
                                                                                                                                                                                                        jazoest: '25453',
                                                                                                                                                                                                            lsd: process.env.FB_LSD || 'AVr9a-pB2Xg',
                                                                                                                                                                                                                __spin_r: '1010210494',
                                                                                                                                                                                                                    __spin_b: 'trunk',
                                                                                                                                                                                                                        __spin_t: '1717977600',
                                                                                                                                                                                                                            fb_api_caller_class: 'RelayModern',
                                                                                                                                                                                                                                fb_api_req_friendly_name: 'CometMarketplaceSearchContentPaginationQuery',
                                                                                                                                                                                                                                    variables,
                                                                                                                                                                                                                                        server_timestamps: 'true',
                                                                                                                                                                                                                                            doc_id: '7111939778879529',
                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                const { data } = await axios.post(FB_SEARCH_URL, params.toString(), {
                                                                                                                                                                                                                                                    headers: FB_HEADERS,
                                                                                                                                                                                                                                                        timeout: 20000,
                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                            // FB returns newline-delimited JSON; take the first object
                                                                                                                                                                                                                                                              const firstLine = typeof data === 'string' ? data.split('\n')[0] : JSON.stringify(data);
                                                                                                                                                                                                                                                                return JSON.parse(firstLine);
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                function extractListings(responseData) {
                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                      const edges =
                                                                                                                                                                                                                                                                            responseData?.data?.marketplace_search?.feed_units?.edges ||
                                                                                                                                                                                                                                                                                  responseData?.data?.viewer?.marketplace_feed_stories?.edges ||
                                                                                                                                                                                                                                                                                        [];
                                                                                                                                                                                                                                                                                            return edges.map(e => e?.node?.listing || e?.node).filter(Boolean);
                                                                                                                                                                                                                                                                                              } catch {
                                                                                                                                                                                                                                                                                                  return [];
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                    function normalize(item, catName, locationName) {
                                                                                                                                                                                                                                                                                                      const id = item?.id || item?.listing_id;
                                                                                                                                                                                                                                                                                                        if (!id) return null;
                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                          const title = cleanText(item?.marketplace_listing_title || item?.name);
                                                                                                                                                                                                                                                                                                            if (!title) return null;
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                              const price = parsePrice(
                                                                                                                                                                                                                                                                                                                  item?.listing_price?.amount ||
                                                                                                                                                                                                                                                                                                                      item?.price?.amount ||
                                                                                                                                                                                                                                                                                                                          item?.formatted_price?.replace(/[^0-9.]/g, '')
                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                              // FB condition strings: "USED_GOOD", "USED_FAIR", "USED_LIKE_NEW", "NEW"
                                                                                                                                                                                                                                                                                                                                const rawCondition = item?.condition || 'used_good';
                                                                                                                                                                                                                                                                                                                                  const condMap = {
                                                                                                                                                                                                                                                                                                                                      'new': 'new',
                                                                                                                                                                                                                                                                                                                                          'used_like_new': 'excellent',
                                                                                                                                                                                                                                                                                                                                              'used_good': 'good',
                                                                                                                                                                                                                                                                                                                                                  'used_fair': 'fair',
                                                                                                                                                                                                                                                                                                                                                      'used_poor': 'poor',
                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                          const condition = condMap[rawCondition.toLowerCase()] || 'good';
                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                            const city = item?.location?.reverse_geocode?.city ||
                                                                                                                                                                                                                                                                                                                                                                item?.location?.city ||
                                                                                                                                                                                                                                                                                                                                                                    locationName.split(',')[0] ||
                                                                                                                                                                                                                                                                                                                                                                        null;
                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                          const baseUrl = item?.canonical_url
                                                                                                                                                                                                                                                                                                                                                                              ? `https://www.facebook.com${item.canonical_url}`
                                                                                                                                                                                                                                                                                                                                                                                  : `https://www.facebook.com/marketplace/item/${id}`;
                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                    const images = [];
                                                                                                                                                                                                                                                                                                                                                                                      const img = item?.primary_listing_photo?.image?.uri ||
                                                                                                                                                                                                                                                                                                                                                                                          item?.listing_photos?.[0]?.image?.uri ||
                                                                                                                                                                                                                                                                                                                                                                                              item?.cover_photo?.photo?.image?.uri;
                                                                                                                                                                                                                                                                                                                                                                                                if (img) images.push(img);
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                  return {
                                                                                                                                                                                                                                                                                                                                                                                                      external_id: String(id),
                                                                                                                                                                                                                                                                                                                                                                                                          platform: 'facebook',
                                                                                                                                                                                                                                                                                                                                                                                                              title,
                                                                                                                                                                                                                                                                                                                                                                                                                  price,
                                                                                                                                                                                                                                                                                                                                                                                                                      currency: item?.listing_price?.currency || 'USD',
                                                                                                                                                                                                                                                                                                                                                                                                                          condition,
                                                                                                                                                                                                                                                                                                                                                                                                                              category: catName,
                                                                                                                                                                                                                                                                                                                                                                                                                                  brand: null, // FB doesn't expose brand as a structured field
                                                                                                                                                                                                                                                                                                                                                                                                                                      model: null,
                                                                                                                                                                                                                                                                                                                                                                                                                                          location_city: city,
                                                                                                                                                                                                                                                                                                                                                                                                                                              location_country: 'US',
                                                                                                                                                                                                                                                                                                                                                                                                                                                  shipping_available: item?.is_shipping_enabled || false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                      shipping_cost: null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                          listing_url: baseUrl,
                                                                                                                                                                                                                                                                                                                                                                                                                                                              affiliate_url: baseUrl, // no affiliate programme
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  image_urls: images,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      seller_name: item?.seller?.name || null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          seller_rating: null, // FB Marketplace doesn't expose ratings
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              seller_reviews: null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  listed_at: item?.creation_time
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ? new Date(item.creation_time * 1000).toISOString()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              : null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                async function upsert(listings) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  for (const l of listings) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!l) continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await db.query(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `INSERT INTO listings (external_id, platform, title, price, currency, condition, category,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          brand, model, location_city, location_country, shipping_available, shipping_cost,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    listing_url, affiliate_url, image_urls, seller_name, seller_rating, seller_reviews, listed_at)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ON CONFLICT (platform, external_id) DO UPDATE SET
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           price=$4, condition=$6, image_urls=$16, updated_at=NOW(), is_active=TRUE`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 [l.external_id, l.platform, l.title, l.price, l.currency, l.condition, l.category,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        l.brand, l.model, l.location_city, l.location_country, l.shipping_available, l.shipping_cost,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               l.listing_url, l.affiliate_url, JSON.stringify(l.image_urls),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      l.seller_name, l.seller_rating, l.seller_reviews, l.listed_at]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async function runFbMarketplaceFetcher() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              logger.info('Starting Facebook Marketplace fetch cycle...');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let total = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  for (const loc of LOCATIONS) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      for (const { q, category } of SEARCH_QUERIES) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const response = await searchFbMarketplace(q, loc);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const raw = extractListings(response);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!raw.length) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              logger.info(`FB Marketplace [${category}/${loc.zip}]: 0 listings (possibly rate-limited)`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const listings = raw.map(item => normalize(item, category, loc.name)).filter(Boolean);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (listings.length) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await upsert(listings);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await scoreListings('facebook', listings.map(l => l.external_id));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              total += listings.length;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              logger.info(`FB Marketplace [${category}/${loc.zip}]: ${listings.length} listings`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await new Promise(r => setTimeout(r, 5000)); // 5s delay — respect rate limits
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    logger.error(`FB Marketplace [${category}/${loc.zip}] error: ${err.message}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await new Promise(r => setTimeout(r, 10000)); // back off on error
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await new Promise(r => setTimeout(r, 8000)); // pause between locations
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await db.query(`UPDATE listings SET is_active=FALSE WHERE platform='facebook' AND updated_at < NOW()-INTERVAL '48 hours'`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                logger.info(`FB Marketplace fetch complete. Total upserted: ${total}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return total;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  module.exports = { runFbMarketplaceFetcher };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
