// ReAmped Sweetwater Used Fetcher
// Sweetwater exposes a public product search API. We filter to Used/Open Box condition.
const axios = require('axios');
const { Pool } = require('pg');
const { scoreListings } = require('../services/scorer');
const { normalizeCondition, cleanText, parsePrice } = require('../utils/normalizers');
const logger = require('../utils/logger');

const db = new Pool({ connectionString: process.env.DATABASE_URL });

const SW_SEARCH_URL = 'https://www.sweetwater.com/store/api/search';
const SW_AFFILIATE_TAG = process.env.SW_AFFILIATE_ID || '';

const CATEGORIES = [
  { query: 'used electric guitar',  name: 'guitar' },
    { query: 'used bass guitar',      name: 'bass' },
      { query: 'used amplifier',        name: 'amp' },
        { query: 'used effects pedal',    name: 'pedal' },
          { query: 'used keyboard',         name: 'keys' },
            { query: 'used drum',             name: 'drum' },
              { query: 'used acoustic guitar',  name: 'acoustic-guitar' },
                { query: 'used audio interface',  name: 'recording' },
                ];

                async function fetchPage(query, page = 1) {
                  const { data } = await axios.get(SW_SEARCH_URL, {
                      params: {
                            q: query,
                                  condition: 'used,open-box',
                                        page,
                                              per_page: 48,
                                                  },
                                                      headers: {
                                                            'User-Agent': 'Mozilla/5.0 (compatible; ReAmped/1.0; +https://reamped.app)',
                                                                  Accept: 'application/json',
                                                                        Referer: 'https://www.sweetwater.com/c773--Used_Gear',
                                                                            },
                                                                                timeout: 20000,
                                                                                  });
                                                                                    return data;
                                                                                    }

                                                                                    function normalize(product, catName) {
                                                                                      const id = product.sku || product.id || null;
                                                                                        if (!id) return null;

                                                                                          const title = cleanText(product.name || product.title);
                                                                                            if (!title) return null;

                                                                                              const price = parsePrice(product.price?.sale || product.price?.regular || product.salePrice || product.price);
                                                                                                const brand = product.brand || product.manufacturer || null;
                                                                                                  const model = cleanText(product.model || product.partNumber || null);

                                                                                                    // Sweetwater condition strings: "Used", "Open Box", "B-Stock"
                                                                                                      const rawCondition = product.condition || 'good';
                                                                                                        const conditionMap = { 'used': 'good', 'open box': 'excellent', 'open-box': 'excellent', 'b-stock': 'good' };
                                                                                                          const condition = conditionMap[rawCondition.toLowerCase()] || normalizeCondition(rawCondition);
                                                                                                          
                                                                                                            const slug = product.url || product.slug || '';
                                                                                                              const baseUrl = slug.startsWith('http') ? slug : `https://www.sweetwater.com${slug}`;
                                                                                                                const affiliateUrl = SW_AFFILIATE_TAG
                                                                                                                    ? `${baseUrl}${baseUrl.includes('?') ? '&' : '?'}affiliate_id=${SW_AFFILIATE_TAG}&utm_source=reamped`
                                                                                                                        : baseUrl;
                                                                                                                        
                                                                                                                          const images = [];
                                                                                                                            if (product.images?.[0]) images.push(typeof product.images[0] === 'string' ? product.images[0] : product.images[0].url);
                                                                                                                              else if (product.image) images.push(typeof product.image === 'string' ? product.image : product.image.url);
                                                                                                                                else if (product.thumbnail) images.push(product.thumbnail);
                                                                                                                                
                                                                                                                                  return {
                                                                                                                                      external_id: String(id),
                                                                                                                                          platform: 'sweetwater',
                                                                                                                                              title,
                                                                                                                                                  price,
                                                                                                                                                      currency: 'USD',
                                                                                                                                                          condition,
                                                                                                                                                              category: catName,
                                                                                                                                                                  brand,
                                                                                                                                                                      model,
                                                                                                                                                                          location_city: 'Fort Wayne',
                                                                                                                                                                              location_country: 'US',
                                                                                                                                                                                  shipping_available: true,
                                                                                                                                                                                      shipping_cost: 0, // Sweetwater offers free shipping
                                                                                                                                                                                          listing_url: baseUrl,
                                                                                                                                                                                              affiliate_url: affiliateUrl,
                                                                                                                                                                                                  image_urls: images,
                                                                                                                                                                                                      seller_name: 'Sweetwater',
                                                                                                                                                                                                          seller_rating: 4.5, // Sweetwater has excellent reputation
                                                                                                                                                                                                              seller_reviews: null,
                                                                                                                                                                                                                  listed_at: product.dateAdded || product.created_at || null,
                                                                                                                                                                                                                    };
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    async function upsert(listings) {
                                                                                                                                                                                                                      for (const l of listings) {
                                                                                                                                                                                                                          if (!l) continue;
                                                                                                                                                                                                                              await db.query(
                                                                                                                                                                                                                                    `INSERT INTO listings (external_id, platform, title, price, currency, condition, category,
                                                                                                                                                                                                                                              brand, model, location_city, location_country, shipping_available, shipping_cost,
                                                                                                                                                                                                                                                        listing_url, affiliate_url, image_urls, seller_name, seller_rating, seller_reviews, listed_at)
                                                                                                                                                                                                                                                               VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20)
                                                                                                                                                                                                                                                                      ON CONFLICT (platform, external_id) DO UPDATE SET
                                                                                                                                                                                                                                                                               price=$4, condition=$6, affiliate_url=$15, image_urls=$16,
                                                                                                                                                                                                                                                                                        updated_at=NOW(), is_active=TRUE`,
                                                                                                                                                                                                                                                                                              [l.external_id, l.platform, l.title, l.price, l.currency, l.condition, l.category,
                                                                                                                                                                                                                                                                                                     l.brand, l.model, l.location_city, l.location_country, l.shipping_available, l.shipping_cost,
                                                                                                                                                                                                                                                                                                            l.listing_url, l.affiliate_url, JSON.stringify(l.image_urls),
                                                                                                                                                                                                                                                                                                                   l.seller_name, l.seller_rating, l.seller_reviews, l.listed_at]
                                                                                                                                                                                                                                                                                                                       );
                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                         async function runSweetwaterFetcher() {
                                                                                                                                                                                                                                                                                                                           logger.info('Starting Sweetwater Used fetch cycle...');
                                                                                                                                                                                                                                                                                                                             let total = 0;
                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                               for (const cat of CATEGORIES) {
                                                                                                                                                                                                                                                                                                                                   try {
                                                                                                                                                                                                                                                                                                                                         for (let page = 1; page <= 3; page++) {
                                                                                                                                                                                                                                                                                                                                                 const data = await fetchPage(cat.query, page);
                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                         const products = data?.results || data?.products || data?.items || [];
                                                                                                                                                                                                                                                                                                                                                                 if (!products.length) break;
                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                         const listings = products.map(p => normalize(p, cat.name)).filter(Boolean);
                                                                                                                                                                                                                                                                                                                                                                                 if (!listings.length) break;
                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                         await upsert(listings);
                                                                                                                                                                                                                                                                                                                                                                                                 await scoreListings('sweetwater', listings.map(l => l.external_id));
                                                                                                                                                                                                                                                                                                                                                                                                         total += listings.length;
                                                                                                                                                                                                                                                                                                                                                                                                                 logger.info(`Sweetwater [${cat.name}] page ${page}: ${listings.length} listings`);
                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                         // Check if there are more pages
                                                                                                                                                                                                                                                                                                                                                                                                                                 const totalPages = data?.pagination?.totalPages || data?.total_pages || 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                         if (page >= totalPages) break;
                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                 await new Promise(r => setTimeout(r, 3000));
                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                           } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 logger.error(`Sweetwater [${cat.name}] error: ${err.message}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         await new Promise(r => setTimeout(r, 4000));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             await db.query(`UPDATE listings SET is_active=FALSE WHERE platform='sweetwater' AND updated_at < NOW()-INTERVAL '48 hours'`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               logger.info(`Sweetwater fetch complete. Total upserted: ${total}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return total;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 module.exports = { runSweetwaterFetcher };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
